ogrenci s1 = new ogrenci();
s1.firstName = 'Meric';
s1.lastName = 'Doe';
s1.className = '1A';
s1.art = true;
s1.sports = false;
s1.mathGrade = 95;
s1.fenGrade = 98;
s1.language = 'English';

system.debug(s1);

ogrenci s2 = new ogrenci();
s2.firstName = 'Sevilay';
s2.lastName = 'Doe';
s2.className = '2A';
s2.art = true;
s2.sports = false;
s2.mathGrade = 100;
s2.fenGrade = 92;
s2.language = 'Greek';

system.debug(s2);