public class Address1 {
    public void Address1() {
    string yourName = 'Meric Ikikol';
    system.debug('Your name is: ' + yourName + '.');
    
    integer numberOfMembers = 4;
    system.debug('Your total number of members in your family is: ' + numberOfMembers + '.');

    string houseName = 'Adalet';
    system.debug('Your house name is: ' + houseName + '.');

    integer houseNumber = 17;
    system.debug('Your house number is: ' + houseNumber + '.');

    string streetName = 'Sapphire';
    system.debug('Your street name is: ' + streetName + '.');
    
    string cityName = 'Toronto';
    system.debug('Your city name is: ' + cityName + '.');

    string stateName = 'Ontario';
    system.debug('Your state name is: ' + stateName + '.');

    string stateIsoCode = 'ON';
    system.debug('Your state Iso code is: ' + stateIsoCode + '.');

    string countryName = 'Canada';
    system.debug('Your country name is: ' + countryName  + '.');

    string countryIsoCode = 'CA';
    system.debug('Your country Iso code is: ' + countryIsoCode + '.');

    string zipCode = '4E6 A7G';
    system.debug('Your zip code is: ' + zipCode + '.');

    Boolean currentHome = true;
    system.debug('Is this your current home or not is: ' + currentHome);
    }
}
